#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
ARGS=4
if [ $# -eq $ARGS ]
then
        scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/$1"

else
        echo  "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

fi;
